### PR TITLE
Support CMake builds

### PR DESCRIPTION
**Pull request by grisumbras**

### CODE REVIEW

**Comment by vinniefalco** [comment]
Doesn't seem to work, because the cmake/ directory is missing:
```
$ cmake -G "Visual Studio 16 2019" -A x64 -B bin64 -DCMAKE_TOOLCHAIN_FILE=cmake/toolchains/msvc.cmake
CMake Error at C:/Program Files/CMake/share/cmake-3.17/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: cmake/toolchains/msvc.cmake
Call Stack (most recent call first):
  CMakeLists.txt:16 (project)
```

**Comment by vinniefalco** [comment]
Okay, copying the cmake/ directory from JSON makes things work, so I will amend your commit locally and merge this. 

However, there is this _deps/test project which only has a CMakeLists.txt which I don't understand the purpose of? See:

image

**Comment by grisumbras** [comment]
Usually toolchain files isn't something a project provides, but something a user provides. But sure, I can see how it can be convenient.

**Comment by vinniefalco** [comment]
If the user is Drone CI or a full build of the Boost libraries, then where would the toolchain files come from?

**Comment by grisumbras** [comment]
CI runs in some specifically configured environment, so either the toolchain file should already be somewhere on the system, or CI should create it, or pull it from somewhere (like a special project with toolchain files).

**Pull request closed without merging**
